# Generated by Django 4.2.1 on 2023-06-27 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameBird', models.CharField(max_length=100, verbose_name='Bird-Name')),
                ('ecorregion', models.CharField(max_length=100, verbose_name='Ecorregion')),
                ('latitude', models.FloatField(verbose_name='Latitude')),
                ('longitude', models.FloatField(verbose_name='Longitude')),
            ],
            options={
                'verbose_name': 'Location',
                'verbose_name_plural': 'Locations',
                'ordering': ['nameBird'],
            },
        ),
    ]
