# Generated by Django 4.2.1 on 2023-06-30 03:10

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bird',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('nombre_cientifico', models.CharField(max_length=100)),
                ('nombre_ingles', models.CharField(max_length=100)),
                ('descripcion', models.TextField(max_length=1000)),
                ('imagen', models.ImageField(default='bird_images/default.jpg', upload_to='bird_images/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'gif'])])),
                ('voz', models.CharField(max_length=50)),
                ('alimentacion', models.CharField(max_length=100)),
                ('cria', models.CharField(max_length=100)),
                ('status_conservacion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('familia', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Familia',
                'verbose_name_plural': 'Familias',
            },
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupo', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Habitat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('habitat', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MovimientoEstacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temporada', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Movimiento estacional',
                'verbose_name_plural': 'Movimientos estacionales',
            },
        ),
        migrations.CreateModel(
            name='Plumaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plumaje', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='TamanioForma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tamanio', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Tamaño y forma',
                'verbose_name_plural': 'Tamaños y formas',
            },
        ),
        migrations.CreateModel(
            name='LineaAvistaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=1)),
                ('latitud', models.FloatField()),
                ('longitud', models.FloatField()),
                ('id_ave', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='appves.bird')),
            ],
        ),
    ]
