# Generated by Django 4.2.1 on 2023-06-30 00:38

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('familia', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Familia',
                'verbose_name_plural': 'Familias',
            },
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupo', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Habitat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('habitat', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MovimientoEstacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temporada', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Movimiento estacional',
                'verbose_name_plural': 'Movimientos estacionales',
            },
        ),
        migrations.CreateModel(
            name='Plumaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plumaje', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='TamanioForma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tamanio', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Tamaño y forma',
                'verbose_name_plural': 'Tamaños y formas',
            },
        ),
        migrations.CreateModel(
            name='Bird',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('nombre_cientifico', models.CharField(max_length=100)),
                ('nombre_ingles', models.CharField(max_length=100)),
                ('descripcion', models.TextField(max_length=1000)),
                ('imagen', models.ImageField(default='bird_images/default.jpg', upload_to='bird_images/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'gif'])])),
                ('voz', models.CharField(max_length=50)),
                ('alimentacion', models.CharField(max_length=100)),
                ('cria', models.CharField(max_length=100)),
                ('status_conservacion', models.CharField(max_length=100)),
                ('cabeza', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cabeza', to='appves.tamanioforma')),
                ('cuello_vuelo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cuello_vuelo', to='appves.tamanioforma')),
                ('familia', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='appves.family')),
                ('forma_alas', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alas', to='appves.tamanioforma')),
                ('forma_cola', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forma_cola', to='appves.tamanioforma')),
                ('grupo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='appves.grupo')),
                ('habitat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='appves.habitat')),
                ('largo_cola', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='largo_cola', to='appves.tamanioforma')),
                ('largo_cuello', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cuello', to='appves.tamanioforma')),
                ('largo_patas', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patas', to='appves.tamanioforma')),
                ('largo_pico', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pico', to='appves.tamanioforma')),
                ('movimientos_estacionales', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='appves.movimientoestacion')),
                ('patron_coloracion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='appves.plumaje')),
                ('status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='appves.status')),
                ('tamanio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tamanio_ave', to='appves.tamanioforma')),
            ],
        ),
    ]
