# Generated by Django 4.2.1 on 2023-07-15 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appves', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineaavistaje',
            name='id_avistaje',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.avistaje'),
        ),
        migrations.AddField(
            model_name='bird',
            name='cabeza',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cabeza', to='appves.tamanioforma'),
        ),
        migrations.AddField(
            model_name='bird',
            name='cuello_vuelo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cuello_vuelo', to='appves.tamanioforma'),
        ),
        migrations.AddField(
            model_name='bird',
            name='familia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='appves.family'),
        ),
        migrations.AddField(
            model_name='bird',
            name='forma_alas',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alas', to='appves.tamanioforma'),
        ),
        migrations.AddField(
            model_name='bird',
            name='forma_cola',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forma_cola', to='appves.tamanioforma'),
        ),
        migrations.AddField(
            model_name='bird',
            name='grupo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='appves.grupo'),
        ),
        migrations.AddField(
            model_name='bird',
            name='habitat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='appves.habitat'),
        ),
        migrations.AddField(
            model_name='bird',
            name='largo_cola',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='largo_cola', to='appves.tamanioforma'),
        ),
        migrations.AddField(
            model_name='bird',
            name='largo_cuello',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cuello', to='appves.tamanioforma'),
        ),
        migrations.AddField(
            model_name='bird',
            name='largo_patas',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patas', to='appves.tamanioforma'),
        ),
        migrations.AddField(
            model_name='bird',
            name='largo_pico',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pico', to='appves.tamanioforma'),
        ),
        migrations.AddField(
            model_name='bird',
            name='movimientos_estacionales',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='appves.movimientoestacion'),
        ),
        migrations.AddField(
            model_name='bird',
            name='patron_coloracion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='appves.plumaje'),
        ),
        migrations.AddField(
            model_name='bird',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='appves.status'),
        ),
        migrations.AddField(
            model_name='bird',
            name='status_conservacion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='appves.statusconservacion'),
        ),
        migrations.AddField(
            model_name='bird',
            name='tamanio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tamanio_ave', to='appves.tamanioforma'),
        ),
    ]
