# Generated by Django 4.2.1 on 2023-05-30 03:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appves', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bird',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('nombre_cientifico', models.CharField(max_length=100)),
                ('nombre_ingles', models.CharField(max_length=100)),
                ('descripcion', models.TextField(max_length=1000)),
                ('voz', models.CharField(max_length=50)),
                ('alimentacion', models.CharField(max_length=100)),
                ('cria', models.CharField(max_length=100)),
                ('status_conservacion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TamanioForma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tamanio', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Tamaño y forma',
                'verbose_name_plural': 'Tamaños y formas',
            },
        ),
        migrations.AlterModelOptions(
            name='family',
            options={'verbose_name': 'Familia', 'verbose_name_plural': 'Familias'},
        ),
        migrations.AlterModelOptions(
            name='movimientoestacion',
            options={'verbose_name': 'Movimiento estacional', 'verbose_name_plural': 'Movimientos estacionales'},
        ),
        migrations.AlterField(
            model_name='family',
            name='familia',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='grupo',
            name='grupo',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='habitat',
            name='habitat',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='movimientoestacion',
            name='temporada',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='plumaje',
            name='plumaje',
            field=models.CharField(max_length=50),
        ),
        migrations.DeleteModel(
            name='Birds',
        ),
        migrations.DeleteModel(
            name='TamanioFormas',
        ),
        migrations.AddField(
            model_name='bird',
            name='cabeza',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cabeza', to='appves.tamanioforma'),
        ),
        migrations.AddField(
            model_name='bird',
            name='cuello_vuelo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cuello_vuelo', to='appves.tamanioforma'),
        ),
        migrations.AddField(
            model_name='bird',
            name='familia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='appves.family'),
        ),
        migrations.AddField(
            model_name='bird',
            name='forma_alas',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alas', to='appves.tamanioforma'),
        ),
        migrations.AddField(
            model_name='bird',
            name='forma_cola',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forma_cola', to='appves.tamanioforma'),
        ),
        migrations.AddField(
            model_name='bird',
            name='grupo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='appves.grupo'),
        ),
        migrations.AddField(
            model_name='bird',
            name='habitat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='appves.habitat'),
        ),
        migrations.AddField(
            model_name='bird',
            name='largo_cola',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='largo_cola', to='appves.tamanioforma'),
        ),
        migrations.AddField(
            model_name='bird',
            name='largo_cuello',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cuello', to='appves.tamanioforma'),
        ),
        migrations.AddField(
            model_name='bird',
            name='largo_patas',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patas', to='appves.tamanioforma'),
        ),
        migrations.AddField(
            model_name='bird',
            name='largo_pico',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pico', to='appves.tamanioforma'),
        ),
        migrations.AddField(
            model_name='bird',
            name='movimientos_estacionales',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='appves.movimientoestacion'),
        ),
        migrations.AddField(
            model_name='bird',
            name='patron_coloracion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='appves.plumaje'),
        ),
        migrations.AddField(
            model_name='bird',
            name='tamanio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tamanio_ave', to='appves.tamanioforma'),
        ),
    ]
