# Generated by Django 4.2.1 on 2023-06-10 05:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appves', '0002_bird_tamanioforma_alter_family_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bird',
            name='imagen',
            field=models.ImageField(default='bird_images/default.jpg', upload_to='bird_images/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'gif'])]),
        ),
    ]
