# Generated by Django 4.2.1 on 2023-06-19 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appves', '0003_bird_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=30)),
            ],
        ),
    ]
