# Generated by Django 4.2.1 on 2023-06-28 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_avistaje_fecha_creacion'),
        ('appves', '0005_bird_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='LineaAvistaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=1)),
                ('latitud', models.FloatField()),
                ('longitud', models.FloatField()),
                ('id_ave', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='appves.bird')),
                ('id_avistaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.avistaje')),
            ],
        ),
    ]
