# Generated by Django 4.2.1 on 2023-07-28 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='avistaje',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
