# Generated by Django 4.2.1 on 2023-06-27 18:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_province_alter_user_province'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avistaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_avistaje', models.CharField(max_length=50)),
                ('fecha_creacion', models.DateField(default=django.utils.timezone.now)),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
