# Generated by Django 4.2.1 on 2023-06-27 21:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_avistaje'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avistaje',
            name='fecha_creacion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
